from building import *

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = []
src     += Glob('eMPL/*.c')
src     += Glob('rtt_porting/*.c')

path    = []
path    += [cwd + '/eMPL']
path    += [cwd + '/rtt_porting']

group = DefineGroup('Drivers', src, depend = [], CPPPATH = path)

Return('group')
