from building import *

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('*.c')

path    = [cwd]

#group = DefineGroup('Drivers', src, depend = ['RT_USING_NB_LED'], CPPPATH = path)
group = DefineGroup('Drivers', src, depend = [], CPPPATH = path)

Return('group')
