from building import *

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('*.c')

path    = [cwd]

# group = DefineGroup('Drivers', src, depend = ['BSP_USING_SPI2'], CPPPATH = path)
group = DefineGroup('Drivers', src, depend = [], CPPPATH = path)

Return('group')
